// Multitasking website/src/app/pagination.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-pagination',
  templateUrl: './pagination.component.html',
  styleUrls: ['./pagination.component.css']
})
export class PaginationComponent {
  pages: number[] = [1, 2, 3, 4, 5, 6, 7, 8, 9];
}

<div class="pagination-container">
    <div class="pagination">
      <span class="arrow">&larr;</span> Older
      <span class="pages">
        <span *ngFor="let page of pages" [class.highlight]="page === 2" class="page">{{ page }}</span>
      </span>
      Newer <span class="arrow">&rarr;</span>
    </div>
  </div>

// react-app/src/Pagination.js
import React from 'react';
import './Pagination.css';

const Pagination = () => {
  return (
    <div className="pagination-container">
      <div className="pagination">
        <span className="arrow">&larr;</span> Older
        <span className="pages">
          {Array.from({ length: 9 }).map((_, index) => (
            <span className="page" key={index}>{index + 1}</span>
          ))}
        </span>
        Newer <span className="arrow">&rarr;</span>
      </div>
    </div>
  );
};

export default Pagination;
